name: 🛡️ Vulnerability Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit Security Scan
        run: bandit -r backend/ -ll
